[phases.setup]
nixPkgs = ["chromium", "nss", "atk", "cups", "libdrm", "libxkbcommon", "mesa"]

[phases.install]
cmds = ["npm install -g pnpm", "pnpm install"]

[phases.build]
cmds = ["pnpm build"]

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/nix/var/nix/profiles/default/bin/chromium"
